### ISSUE TITLE
Critical Bug Report: Upstream `main` Branch is Completely Broken (Mangled Git Merges & Syntax Errors)

### ISSUE THREAD

**Issue by ranbeer06052009** [ronisarkarexe/story-spark-ai#6424]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description
I pulled the latest code from the `origin/main` (upstream) repository and found that the branch is currently in an unbuildable state. Both the frontend and backend workspaces fail to compile due to numerous severe syntax errors and unresolved/mangled Git merge conflict markers that were accidentally committed to the repository.

### Backend Build Failures
Running `npm run build` in `story-spark-ai-backend` throws the following errors:
```text
src/server.ts(179,8): error TS1472: 'catch' or 'finally' expected.
src/server.ts(180,6): error TS1128: Declaration or statement expected.
src/utils/contextCompressor.ts(72,2): error TS1005: ',' expected.
src/utils/promptSecurity.ts(154,1): error TS1005: '}' expected.
```
**Root Cause for `server.ts`:**
Around line 175 in `backend/src/server.ts`, there is a severely mangled Socket.IO configuration block resulting from a bad merge:
```typescript
// Mangled code in main:
        methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
        credentials: true,
      },
    });

    io.use(socketRateLimiter);
```
Additionally, `backend/src/utils/__tests__/pagination.helper.test.ts` still contains raw Git conflict markers (`<<<<<<< HEAD`).

### Frontend Build Failures
Running `npm run build` in `story-spark-ai-frontend` also throws numerous errors:
```text
src/components/AudioPlayer.tsx(140,5): error TS1005: ',' expected.
src/components/stories/BranchingStory.tsx(118,5): error TS1005: ',' expected.
src/hooks/useSpeechSynthesis.ts(413,3): error TS1128: Declaration or statement expected.
src/utils/genreAnalyzer.ts(46,6): error TS1005: ',' expected.
```

### Affected Files with Residual Conflict Markers
A quick `git grep "======="` reveals several files still contain either raw conflict markers or mangled code chunks where someone deleted the markers but left the duplicated code:
- `backend/src/app.ts`
- `backend/src/shared/__tests__/pick.test.ts`
- `backend/src/utils/__tests__/pagination.helper.test.ts`
- `frontend/src/App.tsx`
i want to work on these issues . /assign under gssoc'26 

### Steps to reproduce

1. `git fetch origin main`
2. `git checkout origin/main`
3. Run `npm install`
4. Run `npm run build -w story-spark-ai-backend` and observe the crashes.
5. Run `npm run build -w story-spark-ai-frontend` and observe the crashes.

### Record

- [x] I agree to follow this project's Code of Conduct
- [x] I want to work on this issue
